# Generated by Django 2.2.7 on 2020-01-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191211_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_desc',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
