# Generated by Django 2.2.7 on 2020-01-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uploadedfile_file_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_tag',
            field=models.CharField(default='ZSZI', max_length=20),
        ),
    ]
