# Generated by Django 2.2.7 on 2020-01-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_uploadedfile_file_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=250)),
                ('model_desc', models.TextField(default='', max_length=2000)),
                ('chosen_file', models.CharField(max_length=100)),
                ('qv', models.FloatField()),
                ('q', models.FloatField()),
                ('v', models.FloatField()),
                ('cp_m', models.FloatField()),
                ('ro_m', models.FloatField()),
                ('mi_m', models.FloatField()),
                ('lam_m', models.FloatField()),
                ('cp', models.FloatField()),
                ('ro', models.FloatField()),
                ('alfa', models.FloatField()),
                ('H', models.FloatField()),
                ('D_b', models.FloatField()),
                ('d_out', models.FloatField()),
                ('d_inn', models.FloatField()),
                ('r_g', models.FloatField()),
            ],
        ),
    ]
