# Generated by Django 2.2.7 on 2020-01-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_parametersmodel_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersmodel',
            name='T_g',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
