# Generated by Django 2.2.7 on 2020-01-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_parametersmodel_t_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersmodel',
            name='T_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametersmodel',
            name='alfa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametersmodel',
            name='d_inn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametersmodel',
            name='d_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametersmodel',
            name='lam_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametersmodel',
            name='mi_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametersmodel',
            name='q',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametersmodel',
            name='qv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametersmodel',
            name='r_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametersmodel',
            name='v',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
